openapi: 3.0.4
info:
  title: API - Solicitar Equipamentos e Gerar Nota Fiscal
  version: 1.0.0
  description: Endpoint para solicitar equipamentos e gerar uma Nota Fiscal.

servers:
  - url: https://api-bus-dev.w4b.app
    description: Ambiente de desenvolvimento API Bus

paths:
  /DomainFunctions/MatheusCardoso/2025_1/SolicitarEquipamentosEGerarNF:
    post:
      summary: Solicita equipamentos e gera uma Nota Fiscal
      description: Endpoint para solicitar equipamentos e gerar uma Nota Fiscal.
      operationId: SolicitarEquipamentosEGerarNF
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SolicitarEquipamentosRequest"
      responses:
        "200":
          description: Nota Fiscal gerada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotaFiscal"
        "400":
          description: Requisição inválida
        "500":
          description: Erro interno do servidor

components:
  schemas:
    SolicitarEquipamentosRequest:
      type: object
      properties:
        NomeSolicitante:
          type: string
          description: Nome da pessoa que está solicitando os equipamentos
          example: Matheus Cardoso
        Departamento:
          type: string
          description: Nome do departamento solicitante
          example: TI
        EquipamentosSolicitados:
          type: array
          description: Lista de equipamentos solicitados
          items:
            type: string
            example: Notebook
      required:
        - NomeSolicitante
        - EquipamentosSolicitados

    NotaFiscal:
      type: object
      properties:
        NumeroNF:
          type: string
          description: Número da nota fiscal gerada
          example: "12345"
        DataChegadaEquipamentos:
          type: string
          format: date-time
          description: Data estimada de chegada dos equipamentos
          example: "2025-11-30T14:00:00Z"
      required:
        - NumeroNF
        - DataChegadaEquipamentos
